
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/dev/mingw64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/dev/mingw64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/dev/mingw64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/dev/mingw64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine версии 16.11.2+f32259642 для .NET Framework
      (C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
      
      Сборка начата 15.12.2023 18:11:05.
      Проект "C:\\Learn\\Yandex\\cpp-transport-catalogue\\transport-catalogue\\CMakeFiles\\3.27.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Learn\\Yandex\\cpp-transport-catalogue\\transport-catalogue\\CMakeFiles\\3.27.2\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "C:\\Learn\\Yandex\\cpp-transport-catalogue\\transport-catalogue\\CMakeFiles\\3.27.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.79
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Learn/Yandex/cpp-transport-catalogue/transport-catalogue/CMakeFiles/3.27.2/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/dev/mingw64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/dev/mingw64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Learn/Yandex/cpp-transport-catalogue/transport-catalogue/CMakeFiles/CMakeScratch/TryCompile-nm3tms"
      binary: "C:/Learn/Yandex/cpp-transport-catalogue/transport-catalogue/CMakeFiles/CMakeScratch/TryCompile-nm3tms"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Learn/Yandex/cpp-transport-catalogue/transport-catalogue/CMakeFiles/CMakeScratch/TryCompile-nm3tms'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_8ed00.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        Microsoft (R) Build Engine версии 16.11.2+f32259642 для .NET Framework
        (C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
        
        Сборка начата 15.12.2023 18:11:06.
        Проект "C:\\Learn\\Yandex\\cpp-transport-catalogue\\transport-catalogue\\CMakeFiles\\CMakeScratch\\TryCompile-nm3tms\\cmTC_8ed00.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_8ed00.dir\\Debug\\".
          Создание каталога "C:\\Learn\\Yandex\\cpp-transport-catalogue\\transport-catalogue\\CMakeFiles\\CMakeScratch\\TryCompile-nm3tms\\Debug\\".
          Создание каталога "cmTC_8ed00.dir\\Debug\\cmTC_8ed00.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_8ed00.dir\\Debug\\cmTC_8ed00.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_8ed00.dir\\Debug\\\\" /Fd"cmTC_8ed00.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\dev\\mingw64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.29.30152 для x64
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_8ed00.dir\\Debug\\\\" /Fd"cmTC_8ed00.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\dev\\mingw64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Learn\\Yandex\\cpp-transport-catalogue\\transport-catalogue\\CMakeFiles\\CMakeScratch\\TryCompile-nm3tms\\Debug\\cmTC_8ed00.exe" /INCREMENTAL /ILK:"cmTC_8ed00.dir\\Debug\\cmTC_8ed00.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Learn/Yandex/cpp-transport-catalogue/transport-catalogue/CMakeFiles/CMakeScratch/TryCompile-nm3tms/Debug/cmTC_8ed00.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Learn/Yandex/cpp-transport-catalogue/transport-catalogue/CMakeFiles/CMakeScratch/TryCompile-nm3tms/Debug/cmTC_8ed00.lib" /MACHINE:X64  /machine:x64 cmTC_8ed00.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_8ed00.vcxproj -> C:\\Learn\\Yandex\\cpp-transport-catalogue\\transport-catalogue\\CMakeFiles\\CMakeScratch\\TryCompile-nm3tms\\Debug\\cmTC_8ed00.exe
        FinalizeBuildStatus:
          Файл "cmTC_8ed00.dir\\Debug\\cmTC_8ed00.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_8ed00.dir\\Debug\\cmTC_8ed00.tlog\\cmTC_8ed00.lastbuildstate".
        Сборка проекта "C:\\Learn\\Yandex\\cpp-transport-catalogue\\transport-catalogue\\CMakeFiles\\CMakeScratch\\TryCompile-nm3tms\\cmTC_8ed00.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.36
        
      exitCode: 0
...
